### ISSUE TITLE
Trojan program !?!?!?!??!?!?

### ISSUE THREAD

**Issue by Random121** [PringleCPP/JarJar-Launcher#3]
JarJar launcher a trojan?
![chrome_6OflZZyUaG](https://user-images.githubusercontent.com/59186475/123559770-569c1f00-d75b-11eb-8e83-b53e8244fa50.png)

**Comment by Random121** [comment]
I better reinstall my windows now cuz i got trojan 😱

**Comment by charlie272** [comment]
wait is it really is trogen?

**Comment by PringleCPP** [comment]
retard a trojan?

**Comment by Random121** [comment]
Pringle moment?
